name: Release
on:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.18.1"
          registry-url: "https://registry.npmjs.org"
          cache: npm
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_PAT }}
      - name: Build
        run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/npm
            @semantic-release/github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_PAT }}
      - name: Commit Package.json Changes
        run: |
          git config --global user.email "github-actions-bot@users.noreply.github.com"
          git config --global user.name "site-eng-github-actions"
          git commit -am "chore: release"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
