name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2.5.1
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"
          always-auth: true
          cache: npm

      - name: Install npm dependencies
        run: |
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_PAT }}
      - name: Build
        run: npm run build
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: "@washingtonpost/tachyons-css"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_PAT }}
      - run: |
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}
        if: ${{ steps.release.outputs.release_created }}
